package org.utn.presentacion.bot;

public enum TelegramUserBotStatus {
    WELCOME_CHAT,
    INIT_CHAT,
    MAIN_MENU,
    MENU_GET_INCIDENTS_ORDER_BY_LAST_REPORT,
    MENU_GET_INCIDENTS_ORDER_BY_FIRST_REPORT,
    MENU_GET_INCIDENTS_BY_STATUS_WAITING_RESPONSE_STATUS,
    MENU_GET_INCIDENTS_BY_STATUS,
    MENU_GET_INCIDENTS_BY_PLACE
}