package org.utn.bot;

public enum TelegramUserBotState {
    WELCOME_CHAT,
    INIT_CHAT,
    MAIN_MENU,
    MENU_GET_INCIDENTS_ORDER_BY_LAST_REPORT,
    MENU_GET_INCIDENTS_ORDER_BY_FIRST_REPORT,
    MENU_GET_INCIDENTS_BY_ESTADO,
    MENU_GET_INCIDENTS_BY_PLACE,
    SUBMENU_1,
    SUBMENU_2
}