name: Mini Ci

on:
  pull_request:
    branches:
      - main

jobs:
  test_incidents_backoffice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout incidents-backoffice
        uses: actions/checkout@v3
      - name: Set up JDK 17 and Run tests for incidents-backoffice
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests for incidents-backoffice
        run: |
          cd incidents-backoffice
          mvn verify

  test_catalog_code_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout catalog-code-service
        uses: actions/checkout@v3
      - name: Set up JDK 17 and Run tests for catalog-code-service
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests for catalog-code-service
        run: |
          cd catalog-code-service
          mvn verify
